name = "wrapsheet-public"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Serve static files from public folder
[assets]
directory = "./public"

# Custom domain route
routes = [
  { pattern = "wrapsheet.ccorealtors.com", custom_domain = true }
]

[[d1_databases]]
binding = "WRAP_DB"
database_name = "wrap_sheet"
database_id = "fbba489f-fc17-4472-b70f-578ce5fd9933"

# Service Binding to GrowthZone proxy worker
[[services]]
binding = "GZ_PROXY"
service = "gz-realestate-proxy"
